### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by msusur** [angular-translate/bower-angular-translate#15]
Hi,

http://www.nuget.org/packages/AngularTranslate/ seems to be obsolete. Are you guys thinking about updating the nuget as well?

**Comment by knalli** [comment]
Support for anything must be applied here: https://github.com/angular-translate/angular-translate/issues/

We had already some effort for Nuget (see [wip branch](https://github.com/angular-translate/angular-translate/tree/feature/nuget)), but it does not work for us at the moment. We have no working build path for this..
