### ISSUE TITLE
Not working between controllers

### ISSUE THREAD

**Issue by thiagosbrito** [angular-translate/bower-angular-translate#16]
Hi Pascal,

I've tried to use angular-translate, using the static-files module. I've done exactly like you said on the docs, but nothing is happening, no errors, no messages and no translations, i checked on the dev tools on chrome, and the json's files for other languages are loading properly, but the language are not changing.

Looking foward for your answer.

Att

**Comment by knalli** [comment]
Hi @thiagosbrito , please use the https://github.com/angular-translate/angular-translate/issues/ for questions about support. Additionally, I would recommend more details about your issue, i.e. a demo on plnkr/fiddle.
